/* ════════════════════════════════════════════════════════════════════
   PIMS Grunddaten — React 18 + MUI v5. Shared foundation.

   Ignat, 2026-09-16: "update the Grunddaten prototype with MUI elements,
   because we use them in the real product."

   Everything here follows MUI_PORT_BRIEF.md. The theme is copied verbatim
   from projects/q-explorer-mui/app.js — MUI v5 defaults plus exactly four
   deviations measured off ETC's own product screenshots
   (scripts/sample-etc-screenshots.cjs). It is not re-derived here, because
   re-deriving it is how two ports drift apart.

   The domain model and the logic come from data.js, generated by
   scripts/gd-extract-shared.cjs straight out of the vanilla prototype.
   Nothing in this port retypes a data row or a rule.
   ════════════════════════════════════════════════════════════════════ */
const { useState, useMemo, useContext, createContext, useRef, useEffect, useCallback } = React;
const html = htm.bind(React.createElement);
const M = MaterialUI;
const {
  ThemeProvider, createTheme, CssBaseline, AppBar, Toolbar, Box, Button, IconButton,
  Typography, Menu, MenuItem, ListItemText, ListSubheader, Divider, Breadcrumbs, Link,
  Card, CardContent, TextField, Table, TableBody, TableCell, TableContainer, TableHead,
  TableRow, Paper, Chip, Stack, FormControl, InputLabel, Select, InputAdornment, Alert,
  Tooltip, Tabs, Tab, Dialog, DialogTitle, DialogContent, DialogActions, DialogContentText,
  Snackbar, Checkbox, Radio, RadioGroup, FormControlLabel, FormLabel, Switch, Avatar,
  LinearProgress, ToggleButton, ToggleButtonGroup, FormHelperText, TablePagination,
} = M;

/* Material Icons render as ligature TEXT, so without aria-hidden the glyph name
   is concatenated into the accessible name of whatever contains it — screen
   readers announced "Everrunning expand more, button". Decorative at every call
   site; the ones that need a name set aria-label on the button itself. */
const Icon = ({ children, sx, ...rest }) =>
  html`<span className="material-icons" aria-hidden="true"
        style=${{ fontSize: 20, ...(sx || {}) }} ...${rest}>${children}</span>`;

/* ── The theme — copied verbatim, three measured deviations ─────────
   · primary #2196F3 (Blue 500), not MUI's #1976D2 — sampled off an ADD
     EVENT button in ETC's own UI
   · cards outlined, 1px #E7E7E7, no shadow
   · TableHead carries an #F4F4F4 band (MUI's own is transparent)
   Field fill #F0F0F0, 48px filled fields and 36px dense menu items were
   measured too and turned out to be MUI stock — so they are not here.

   The AppBar is NOT one of them. ETC's own product bar is navy #1C2848 and
   the port used it; Ignat, 2026-09-16: "wrong top bar". This prototype's
   chrome is the vanilla's white 52px bar, and a port carries the source
   across — the measured navy belongs to ETC screens, not to this one.
   It also took MUI's light-palette disabled colour onto a dark ground,
   which rendered three nav items at 1.14:1. */
const BAR_BG = '#FFFFFF';
const BAR_H = 52;

const theme = createTheme({
  palette: {
    primary: { main: '#2196F3', dark: '#1769AA', light: '#64B5F6' },
    background: { default: '#FAFAFA' },
  },
  shape: { borderRadius: 4 },
  components: {
    // Ignat, 2026-09-14: "We usually use small. Buttons without shadows."
    MuiButton:      { defaultProps: { size: 'small', disableElevation: true } },
    MuiIconButton:  { defaultProps: { size: 'small' } },
    MuiTextField:   { defaultProps: { size: 'small', variant: 'filled' } },
    MuiFormControl: { defaultProps: { size: 'small', variant: 'filled' } },
    MuiTable:       { defaultProps: { size: 'small' } },
    MuiAppBar:      { defaultProps: { elevation: 0 } },
    MuiToolbar:     { defaultProps: { variant: 'dense' } },
    // measured: TableHead carries a band; MUI's own is transparent
    MuiTableHead:   { styleOverrides: { root: { backgroundColor: '#F4F4F4' } } },
    // measured: cards are a 1px #E7E7E7 hairline, no shadow
    MuiCard:        { defaultProps: { variant: 'outlined' },
                      styleOverrides: { root: { borderColor: '#E7E7E7' } } },
    // measured: the selected menu row is primary 12%, not action.selected grey
    MuiMenuItem:    { styleOverrides: { root: {
                        '&.Mui-selected':       { backgroundColor: 'rgba(33,150,243,0.12)' },
                        '&.Mui-selected:hover': { backgroundColor: 'rgba(33,150,243,0.12)' },
                      } } },
  },
});

/* ── App store ──────────────────────────────────────────────────────
   The vanilla keeps one mutable `state` object and re-renders the world.
   React owns view state here, but the extracted logic in data.js mutates
   the domain arrays in place (stations, displayTexts, playlists …) exactly
   as the vanilla does — rewriting that model would be the "lost the logic"
   mistake again. bump() is the nudge that makes an in-place mutation show
   up, so the two prototypes keep one implementation of every rule. */
const App = createContext(null);
const useApp = () => useContext(App);

/** The view registry. Each views-*.js file registers into it. */
const VIEWS = {};

const INITIAL = {
  view: 'stations',
  selectedId: null,
  selectedLine: null,
  selectedLineId: null,
  search: '',
  lineFilter: '',        // '' = every line. No "All" option — brief §3.
  soundTab: 'tracks',
  soundFilter: '',       // '' = every type
  soundSearch: '',
  plId: null,
  evId: null,
  evDraft: null,
  evSearch: '',
  evPickSearch: '',
  txtSel: [],            // display-text ids, survives paging
  txtLastSel: null,
  txtPage: 0,            // MUI TablePagination is 0-based
  txtPerPage: 10,
};

/* ── Shared components ─────────────────────────────────────────────── */

/**
 * A filter select. No All option — an empty value IS all, the label names
 * the field, and the ✕ clears it. Ignat, 2026-09-15.
 *
 * Removing "All" removes the only thing that named these fields in the
 * vanilla ("Alle Linien", "Alle Typen"), which is why the label is required
 * rather than optional.
 */
function FilterSelect({ label, value, onChange, options, minWidth = 180, id, required }) {
  // The label has to be wired to the Select by id, not just rendered above it:
  // an InputLabel with no `id` and a Select with no `labelId` leaves the
  // combobox with no accessible name at all, and `required` on the FormControl
  // only reaches the aria-hidden native input behind it.
  const labelId = id ? id + '-label' : undefined;
  return html`
    <${FormControl} sx=${{ minWidth }} id=${id} required=${!!required}>
      <${InputLabel} id=${labelId}>${label}<//>
      <${Select} value=${value || ''} label=${label} labelId=${labelId}
        inputProps=${{ 'aria-required': !!required }}
        onChange=${e => onChange(e.target.value)}
        endAdornment=${value ? html`
          <${InputAdornment} position="end" sx=${{ mr: 3 }}>
            <${IconButton} aria-label=${'Clear ' + label} onClick=${() => onChange('')}>
              <${Icon} sx=${{ fontSize: 18 }}>close<//>
            <//>
          <//>` : null}>
        ${options.map(o => html`<${MenuItem} key=${o.value} value=${o.value}>${o.label}<//>`)}
      <//>
    <//>`;
}

/**
 * Page header: breadcrumb, title, subtitle, and the action in the corner.
 * Brief §3 — breadcrumbs plus a corner action button, no back buttons.
 */
function PageHeader({ crumbs, title, titleAfter, subtitle, action }) {
  return html`
    <${Box} sx=${{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between',
                   px: 3, py: 2.5, bgcolor: '#fff', borderBottom: '1px solid #E7E7E7' }}>
      <${Box}>
        ${crumbs && crumbs.length ? html`
          <${Breadcrumbs} separator=${html`<${Icon} sx=${{ fontSize: 16 }}>chevron_right<//>`} sx=${{ mb: .5 }}>
            ${crumbs.map((cr, i) => cr.onClick
              ? html`<${Link} key=${i} component="button" underline="hover" color="inherit"
                       variant="body2" onClick=${cr.onClick}>${cr.label}<//>`
              : html`<${Typography} key=${i} variant="body2" color="text.secondary">${cr.label}<//>`)}
          <//>` : null}
        <${Stack} direction="row" spacing=${1} alignItems="center">
          <${Typography} variant="h6" sx=${{ fontWeight: 500 }}>${title}<//>
          ${titleAfter}
        <//>
        ${subtitle ? html`<${Typography} variant="body2" color="text.secondary" sx=${{ mt: .25 }}>${subtitle}<//>` : null}
      <//>
      ${action ? html`<${Box} sx=${{ pt: .5 }}>${action}<//>` : null}
    <//>`;
}

/** An outlined section card with a title row. The house style is flat. */
function SectionCard({ title, subtitle, action, children, disablePadding, sx }) {
  return html`
    <${Card} sx=${{ mb: 2, ...(sx || {}) }}>
      ${title ? html`
        <${Box} sx=${{ display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                       gap: 2, px: 2, py: 1.25, borderBottom: '1px solid #E7E7E7' }}>
          <${Stack} direction="row" spacing=${1.5} alignItems="baseline">
            <${Typography} variant="subtitle2" sx=${{ fontWeight: 500 }}>${title}<//>
            ${subtitle ? html`<${Typography} variant="caption" color="text.secondary">${subtitle}<//>` : null}
          <//>
          ${action}
        <//>` : null}
      <${Box} sx=${disablePadding ? { p: 0 } : { p: 2 }}>${children}<//>
    <//>`;
}

/** The BVG line badge. Product-specific colour, so it keeps its own chip. */
function LineBadge({ line, size = 'small' }) {
  if (!line) return null;
  const bg = lineColor[line] || '#666';
  return html`<${Chip} size=${size} label=${line}
    sx=${{ bgcolor: bg, color: line === 'U4' ? '#000' : '#fff', fontWeight: 700,
           height: 20, '& .MuiChip-label': { px: 1, fontSize: 11 } }} />`;
}

/** Full-width page body with the 24px gutters the brief asks for. */
function PageBody({ children, sx }) {
  return html`<${Box} sx=${{ px: 3, py: 2.5, ...(sx || {}) }}>${children}<//>`;
}

/**
 * The seven-day period grid — one component, three callers (transfer
 * announcement schedules, the V1 event editor, the V2 station schedule).
 * The vanilla built the same markup three times; the rules are identical,
 * so the component is shared rather than copied.
 *
 *   days       [{ day, slots:[{start,end}] }] — always all seven, in order
 *   allowEmpty a day may hold no periods and reads "keine Wiedergabe"
 *              (music); false keeps at least one period (transfer schedules)
 */
function WeekGrid({ days, onChange, allowEmpty = false, idPrefix = 'wk' }) {
  const { t } = useApp();
  const edit = fn => { const next = days.map(d => ({ day: d.day, slots: d.slots.map(s => ({ ...s })) })); fn(next); onChange(next); };
  const setSlot = (di, si, field, val) => edit(n => { n[di].slots[si][field] = val; });
  const addSlot = di => edit(n => { n[di].slots.push({ start: '09:00', end: '23:00' }); });
  const removeSlot = (di, si) => edit(n => { if (!allowEmpty && n[di].slots.length <= 1) return; n[di].slots.splice(si, 1); });
  const copyDay = di => edit(n => { if (di >= n.length - 1) return; n[di + 1].slots = n[di].slots.map(s => ({ ...s })); });

  const timeField = (di, si, field, slot) => html`
    <${TextField} type="time" value=${slot[field]} id=${`${idPrefix}-${di}-${si}-${field}`}
      ${/* idPrefix is part of every accessible name here: the V2 editor can
            show several grids at once, and "add period 0" in three of them
            names nothing. */ ''}
      inputProps=${{ 'aria-label': `${idPrefix} ${dayLabel(days[di].day)} ${field}` }}
      onChange=${e => setSlot(di, si, field, e.target.value)} sx=${{ width: 132 }} />`;

  // Tag / Beginn / Ende — the vanilla heads all three of its week grids this
  // way and inlines the literals; the shared component dropped them in the
  // first pass and the parity checker is what found it.
  const dayLbl = state.lang === 'de' ? 'Tag' : 'Day';
  const startLbl = state.lang === 'de' ? 'Beginn' : 'Start';
  const endLbl = state.lang === 'de' ? 'Ende' : 'End';

  return html`
    <${TableContainer} sx=${{ maxWidth: 560 }}>
      <${Table} sx=${{ '& td': { borderBottom: 'none', py: .5 } }}>
        <${TableHead}><${TableRow}>
          <${TableCell} sx=${{ width: 48 }}>${dayLbl}<//>
          <${TableCell}>${startLbl}<//>
          <${TableCell} sx=${{ width: 16, px: 0 }} />
          <${TableCell}>${endLbl}<//>
          <${TableCell} />
        <//><//>
        <${TableBody}>
          ${days.map((dayObj, di) => {
            const last = di === days.length - 1;
            const rows = dayObj.slots.length
              ? dayObj.slots.map((slot, si) => {
                  const firstSlot = si === 0, lastSlot = si === dayObj.slots.length - 1;
                  const canRemove = allowEmpty || dayObj.slots.length > 1;
                  return html`
                    <${TableRow} key=${`${di}-${si}`}>
                      ${/* a continuation row leaves the day column empty; it once
                            held a transparent "·" to hold the height, which a
                            screen reader still read out. The time field sets the
                            row height on its own. */ ''}
                      <${TableCell} sx=${{ width: 48, fontWeight: 500 }}>
                        ${firstSlot ? dayLabel(dayObj.day) : ''}
                      <//>
                      <${TableCell}>${timeField(di, si, 'start', slot)}<//>
                      <${TableCell} sx=${{ width: 16, color: 'text.secondary', px: 0 }}>–<//>
                      <${TableCell}>${timeField(di, si, 'end', slot)}<//>
                      <${TableCell} align="right" sx=${{ whiteSpace: 'nowrap' }}>
                        ${/* the vanilla has no i18n key for this one; it inlines the
                              literal, so the literal is what comes across */ ''}
                        <${Tooltip} title=${state.lang === 'de' ? 'Entfernen' : 'Remove'}>
                          <span><${IconButton} disabled=${!canRemove} aria-label=${`${idPrefix} remove period ${di}-${si}`}
                            onClick=${() => removeSlot(di, si)}><${Icon} sx=${{ fontSize: 18 }}>remove<//><//><//>
                        <//>
                        ${lastSlot ? html`
                          <${Tooltip} title=${t('addSlot')}>
                            <${IconButton} aria-label=${`${idPrefix} add period ${di}`} onClick=${() => addSlot(di)}>
                              <${Icon} sx=${{ fontSize: 18 }}>add<//><//>
                          <//>` : null}
                        ${lastSlot && !last ? html`
                          <${Tooltip} title=${t('copyToNext')}>
                            <${IconButton} aria-label=${`${idPrefix} copy day ${di}`} onClick=${() => copyDay(di)}>
                              <${Icon} sx=${{ fontSize: 18 }}>content_copy<//><//>
                          <//>` : null}
                      <//>
                    <//>`;
                })
              : [html`
                  <${TableRow} key=${`${di}-empty`}>
                    <${TableCell} sx=${{ width: 48, fontWeight: 500 }}>${dayLabel(dayObj.day)}<//>
                    <${TableCell} colSpan=${3} sx=${{ color: 'text.disabled', fontStyle: 'italic' }}>${t('msNoPlayback')}<//>
                    <${TableCell} align="right">
                      <${Tooltip} title=${t('addSlot')}>
                        <${IconButton} aria-label=${`${idPrefix} add period ${di}`} onClick=${() => addSlot(di)}>
                          <${Icon} sx=${{ fontSize: 18 }}>add<//><//>
                      <//>
                    <//>
                  <//>`];
            return html`<${React.Fragment} key=${di}>
              ${rows}
              ${last ? null : html`<${TableRow}><${TableCell} colSpan=${5} sx=${{ p: 0 }}>
                <${Box} sx=${{ borderBottom: '1px solid #E7E7E7' }} /><//><//>`}
            <//>`;
          })}
        <//>
      <//>
    <//>`;
}

/**
 * Confirm before a destructive action. MUI Dialog, unstyled — brief §2.
 * `confirmLabel` is required: there is no generic "Delete" string in the
 * vanilla's table, and t() returns the key on a miss, so a default would
 * render the word `delete` as if it were a label.
 */
function ConfirmDialog({ open, title, body, confirmLabel, onConfirm, onClose }) {
  const { t } = useApp();
  return html`
    <${Dialog} open=${!!open} onClose=${onClose}>
      <${DialogTitle}>${title}<//>
      ${body ? html`<${DialogContent}><${DialogContentText}>${body}<//><//>` : null}
      <${DialogActions}>
        <${Button} onClick=${onClose}>${t('cancel')}<//>
        <${Button} color="error" variant="contained" onClick=${onConfirm}>${confirmLabel}<//>
      <//>
    <//>`;
}

/** An empty table body row, so a filtered-to-nothing table still reads. */
function EmptyRow({ colSpan, label }) {
  return html`
    <${TableRow}><${TableCell} colSpan=${colSpan} align="center"
      sx=${{ color: 'text.disabled', py: 4 }}>${label || '—'}<//><//>`;
}
