const { chromium } = require('/home/ubuntu/.openclaw/workspace/node_modules/playwright');
(async()=>{
  const b=await chromium.launch();
  const p=await b.newPage({viewport:{width:1340,height:900}});
  await p.goto('file:///home/ubuntu/.openclaw/workspace/filtering-options/index.html');
  await p.addStyleTag({content:'.page-header{position:static !important}'});
  await p.click('.nav-tab[data-variant="rec"]');
  const f=k=>'#recFilterBar [data-field-key="'+k+'"]';
  await p.locator('#variant-rec .mock-page').screenshot({path:'/tmp/f-default.png'});
  await p.click('#recFilterBar [data-rec-add]');
  await p.click('#recFilterBar [data-rec-add-key="amount"]');
  await p.click(f('amount')+' [data-amount-op="between"]');
  await p.locator(f('amount')+' [data-amount-a]').fill('100');
  await p.locator(f('amount')+' [data-amount-b]').fill('500');
  await p.locator('#variant-rec .mock-page').screenshot({path:'/tmp/f-amount.png'});
  await p.keyboard.press('Escape');
  await p.click(f('date')+' [data-field-trigger]');
  await p.click(f('date')+' [data-option-value="custom"]');
  await p.locator(f('date')+' [data-range-from]').fill('2026-03-01');
  await p.locator(f('date')+' [data-range-to]').fill('2026-03-31');
  await p.locator('#variant-rec .mock-page').screenshot({path:'/tmp/f-date.png'});
  await p.keyboard.press('Escape');
  await p.click('#recFilterBar [data-rec-add]');
  await p.click('#recFilterBar [data-rec-add-key="customer"]');
  await p.locator(f('customer')+' [data-panel-search]').type('ver');
  await p.locator('#variant-rec .mock-page').screenshot({path:'/tmp/f-search.png'});
  await p.keyboard.press('Escape');
  await p.click('#recDeepLinkBtn');
  await p.locator('#variant-rec .mock-page').screenshot({path:'/tmp/f-deeplink.png'});
  console.log('ok');
  await b.close();
})();
